added git status checking in publish script

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,5 +1,12 @@
 #!/bin/bash
 set -e
+
+res=$(git status | grep "nothing to commit" | wc -l)
+if [ "$res" != 1 ]; then
+  echo "Error: unclean working directory, please commit changes first."
+  exit 1
+fi
+
 if [ $# == 1 ]; then
   t=$1
 else
